# Generated by Django 5.2.9 on 2025-12-09 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_portfolio2_port'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Port',
            new_name='Portfolio2',
        ),
    ]
